### ISSUE TITLE
Add screenshot generation to GitHub Actions pipeline

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3477]
- [ ] Add screenshot generation to GitHub Actions pipeline
- [ ] Upload generated screenshots somewhere

```
          steps:
            - name: Upload generated screenshots as build artefacts
              uses: actions/upload-artifact@v2
              with:
                name: homework
                path: math-homework.txt
```
