### ISSUE TITLE
Investigate automating releases to secondary distribution channels

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4580]
- [ ] Investigate automating releases to Amazon App Store (we are currently published there)
- [ ] Investigate automating APK releases to the website
- [ ] Investigate automating APK releases to APKMirror

```
name: Build & upload to Firebase App Distribution 

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build release 
      run: ./gradlew assembleRelease
    - name: Upload to the Amazon AppStore
      uses: ALJAZEERAPLUS/amazon-appstore-action@v1
      with:
        client-id: ${{secrets.AMAZON_APPSTORE_CLIENT_ID}}
        client-secret: ${{secrets.AMAZON_APPSTORE_CLIENT_SECRET}}
        app-id: ${{ secrets.AMAZON_APPSTORE_APP_ID }}
        apk-file: app/build/outputs/apk/release/app-release.apk
```
